import product11 from "./Assets/ProductImage/4 stroke 5HP outboard motor F5A-1.jpg";
import product12 from "./Assets/ProductImage/4 stroke 15HP 323cc OutBoards F15-2.jpg";
import product1main1 from "./Assets/ProductImage/4 stroke 15HP 323cc OutBoards F15-1.jpg";
import product1main2 from "./Assets/ProductImage/4 stroke 15HP 323cc OutBoards F15-main image-2.png";

export const product_data = [
  {
    title: "Rigid Inflatable Boat 3.9m With 40HP Outboard Motor",
    id: 1,
    mainImages: [product1main1,product1main2],
    description_images: [product11,product12],
    category: "Inflatable Boat",
    product_details: {
      Length: "3.1 - 4m",
      Type: "Rigid Boat",
      Paddlers: 2,
      Hull_Material: "Fiberglass",
      Certification: "CE",
      Use: ["Fishing", "Drifting", "funs"],
      Size: "3.9m",
      Model_Number: "RIB390",
      Place_of_Origin: "Jiangsu, China (Mainland)",
      Brand_Name: "SAIL or OEM",
      Boat_type: "Rigid inflatable boat",
      Hull: "Fiber glass",
      People: 5,
      Engine_recommend: "15HP-40HP",
      Brand: "SAIL or OEM",
      Fabric_material: "PVC South Korea original",
      Control: "FRP center console",
      Certificate: "CE",
      Length: "3.9 meters",
      Fuel_tank: "24L",
      Additional_Info: {
        Length: "3900mm",
        Beam: "1820mm",
        Inner_beam: "830mm",
        NO_Of_Chamber: "3",
        Tube_Diameter: "440",
        Max_person: "5",
        Engine_power: "SAIL 15HP /30HP/40HP",
        Net_Weight: "120kgs",
        Box_size: "360 x 130 x 60CM.",
        Come_with:
          "Foot pump, Oars, repair kits, fiber glass center console, soft seat, stainless steel hand holder.",
        Brand: "SAIL or OEM",
      },
      Outboard_motor:
        "SAIL 4-stroke 15HP electric start, Short shaft, remote control box and steering wheel and cables.",
      short_description: "",
    },
  },

  {
    title: "Rigid Inflatable Boat 3.9m With 40HP Outboard Motor",
    id: 2,
    mainImages: [product1main1,product1main2],
    description_images: [product11,product12],
    category: "Water Pump",
    product_details: {
      Length: "3.1 - 4m",
      Type: "Rigid Boat",
      Paddlers: 2,
      Hull_Material: "Fiberglass",
      Certification: "CE",
      Use: ["Fishing", "Drifting", "funs"],
      Size: "3.9m",
      Model_Number: "RIB390",
      Place_of_Origin: "Jiangsu, China (Mainland)",
      Brand_Name: "SAIL or OEM",
      Boat_type: "Rigid inflatable boat",
      Hull: "Fiber glass",
      People: 5,
      Engine_recommend: "15HP-40HP",
      Brand: "SAIL or OEM",
      Fabric_material: "PVC South Korea original",
      Control: "FRP center console",
      Certificate: "CE",
      Length: "3.9 meters",
      Fuel_tank: "24L",
      Additional_Info: {
        Length: "3900mm",
        Beam: "1820mm",
        Inner_beam: "830mm",
        NO_Of_Chamber: "3",
        Tube_Diameter: "440",
        Max_person: "5",
        Engine_power: "SAIL 15HP /30HP/40HP",
        Net_Weight: "120kgs",
        Box_size: "360 x 130 x 60CM.",
        Come_with:
          "Foot pump, Oars, repair kits, fiber glass center console, soft seat, stainless steel hand holder.",
        Brand: "SAIL or OEM",
      },
      Outboard_motor:
        "SAIL 4-stroke 15HP electric start, Short shaft, remote control box and steering wheel and cables.",
      short_description: "",
    },
  },


  {
    title: "Rigid Inflatable Boat 3.9m With 40HP Outboard Motor",
    id: 2,
    mainImages: [product1main1,product1main2],
    description_images: [product11,product12],
    category: "Diesel Engine & Fishing Nets",
    product_details: {
      Length: "3.1 - 4m",
      Type: "Rigid Boat",
      Paddlers: 2,
      Hull_Material: "Fiberglass",
      Certification: "CE",
      Use: ["Fishing", "Drifting", "funs"],
      Size: "3.9m",
      Model_Number: "RIB390",
      Place_of_Origin: "Jiangsu, China (Mainland)",
      Brand_Name: "SAIL or OEM",
      Boat_type: "Rigid inflatable boat",
      Hull: "Fiber glass",
      People: 5,
      Engine_recommend: "15HP-40HP",
      Brand: "SAIL or OEM",
      Fabric_material: "PVC South Korea original",
      Control: "FRP center console",
      Certificate: "CE",
      Length: "3.9 meters",
      Fuel_tank: "24L",
      Additional_Info: {
        Length: "3900mm",
        Beam: "1820mm",
        Inner_beam: "830mm",
        NO_Of_Chamber: "3",
        Tube_Diameter: "440",
        Max_person: "5",
        Engine_power: "SAIL 15HP /30HP/40HP",
        Net_Weight: "120kgs",
        Box_size: "360 x 130 x 60CM.",
        Come_with:
          "Foot pump, Oars, repair kits, fiber glass center console, soft seat, stainless steel hand holder.",
        Brand: "SAIL or OEM",
      },
      Outboard_motor:
        "SAIL 4-stroke 15HP electric start, Short shaft, remote control box and steering wheel and cables.",
      short_description: "",
    },
  },

  {
    title: "Rigid Inflatable Boat 3.9m With 40HP Outboard Motor",
    id: 2,
    mainImages: [product1main1,product1main2],
    description_images: [product11,product12],
    category: "RIB Boat",
    product_details: {
      Length: "3.1 - 4m",
      Type: "Rigid Boat",
      Paddlers: 2,
      Hull_Material: "Fiberglass",
      Certification: "CE",
      Use: ["Fishing", "Drifting", "funs"],
      Size: "3.9m",
      Model_Number: "RIB390",
      Place_of_Origin: "Jiangsu, China (Mainland)",
      Brand_Name: "SAIL or OEM",
      Boat_type: "Rigid inflatable boat",
      Hull: "Fiber glass",
      People: 5,
      Engine_recommend: "15HP-40HP",
      Brand: "SAIL or OEM",
      Fabric_material: "PVC South Korea original",
      Control: "FRP center console",
      Certificate: "CE",
      Length: "3.9 meters",
      Fuel_tank: "24L",
      Additional_Info: {
        Length: "3900mm",
        Beam: "1820mm",
        Inner_beam: "830mm",
        NO_Of_Chamber: "3",
        Tube_Diameter: "440",
        Max_person: "5",
        Engine_power: "SAIL 15HP /30HP/40HP",
        Net_Weight: "120kgs",
        Box_size: "360 x 130 x 60CM.",
        Come_with:
          "Foot pump, Oars, repair kits, fiber glass center console, soft seat, stainless steel hand holder.",
        Brand: "SAIL or OEM",
      },
      Outboard_motor:
        "SAIL 4-stroke 15HP electric start, Short shaft, remote control box and steering wheel and cables.",
      short_description: "",
    },
  },

  {
    title: "3.9m With 40HP Outboard Motor",
    id: 2,
    mainImages: [product1main1,product1main2],
    description_images: [product11,product12],
    category: "Gasoline Generator",
    product_details: {
      Length: "3.1 - 4m",
      Type: "Rigid Boat",
      Paddlers: 2,
      Hull_Material: "Fiberglass",
      Certification: "CE",
      Use: ["Fishing", "Drifting", "funs"],
      Size: "3.9m",
      Model_Number: "RIB390",
      Place_of_Origin: "Jiangsu, China (Mainland)",
      Brand_Name: "SAIL or OEM",
      Boat_type: "Rigid inflatable boat",
      Hull: "Fiber glass",
      People: 5,
      Engine_recommend: "15HP-40HP",
      Brand: "SAIL or OEM",
      Fabric_material: "PVC South Korea original",
      Control: "FRP center console",
      Certificate: "CE",
      Length: "3.9 meters",
      Fuel_tank: "24L",
      Additional_Info: {
        Length: "3900mm",
        Beam: "1820mm",
        Inner_beam: "830mm",
        NO_Of_Chamber: "3",
        Tube_Diameter: "440",
        Max_person: "5",
        Engine_power: "SAIL 15HP /30HP/40HP",
        Net_Weight: "120kgs",
        Box_size: "360 x 130 x 60CM.",
        Come_with:
          "Foot pump, Oars, repair kits, fiber glass center console, soft seat, stainless steel hand holder.",
        Brand: "SAIL or OEM",
      },
      Outboard_motor:
        "SAIL 4-stroke 15HP electric start, Short shaft, remote control box and steering wheel and cables.",
      short_description: "",
    },
  },

  {
    title: "Rigid Inflatable Boat 3.9m With 40HP Outboard Motor",
    id: 2,
    mainImages: [product1main1,product1main2],
    description_images: [product11,product12],
    category: "OutBoard Motor",
    product_details: {
      Length: "3.1 - 4m",
      Type: "Rigid Boat",
      Paddlers: 2,
      Hull_Material: "Fiberglass",
      Certification: "CE",
      Use: ["Fishing", "Drifting", "funs"],
      Size: "3.9m",
      Model_Number: "RIB390",
      Place_of_Origin: "Jiangsu, China (Mainland)",
      Brand_Name: "SAIL or OEM",
      Boat_type: "Rigid inflatable boat",
      Hull: "Fiber glass",
      People: 5,
      Engine_recommend: "15HP-40HP",
      Brand: "SAIL or OEM",
      Fabric_material: "PVC South Korea original",
      Control: "FRP center console",
      Certificate: "CE",
      Length: "3.9 meters",
      Fuel_tank: "24L",
      Additional_Info: {
        Length: "3900mm",
        Beam: "1820mm",
        Inner_beam: "830mm",
        NO_Of_Chamber: "3",
        Tube_Diameter: "440",
        Max_person: "5",
        Engine_power: "SAIL 15HP /30HP/40HP",
        Net_Weight: "120kgs",
        Box_size: "360 x 130 x 60CM.",
        Come_with:
          "Foot pump, Oars, repair kits, fiber glass center console, soft seat, stainless steel hand holder.",
        Brand: "SAIL or OEM",
      },
      Outboard_motor:
        "SAIL 4-stroke 15HP electric start, Short shaft, remote control box and steering wheel and cables.",
      short_description: "",
    },
  },

];
